name: Deploying apt repo
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  unpack-rootfs:
    runs-on: ubuntu-22.04
    steps:
      - name: Checking out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Deploying repo
        uses: Apacelus/apt-repo-action@test
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo_supported_arch: amd64
          repo_supported_version: |
            kinetic
            jammy
          file: test.deb
          file_target_version: kinetic
          public_key: ${{ secrets.PUBLIC }}
          private_key: ${{ secrets.PRIVATE }}
          key_passphrase: ""
