name: Deploying apt repo
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "10 0 * * *" # run at the start of every day after postinstall scripts repo update
  workflow_dispatch:

jobs:
  deploy-repo:
    runs-on: ubuntu-22.04
    steps:
      - name: Checking out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Check if postinstall scripts had an update
      # This oneliner compares the locally stored commit has agains the latest one at the postinstall repo. If they match, the rest of the workflow does not execute
        if: ${{ '$(cat last_commit_sha.txt)' != '$(curl -s https://api.github.com/repos/eupnea-linux/postinstall-scripts/commits/main | jq -r ".sha")' }} 
        # Update local commit sha
        run: echo $(curl -s https://api.github.com/repos/eupnea-linux/postinstall-scripts/commits/main | jq -r '.sha') > ./last_commit_sha.txt
      
      - name: Bump version in control file
        run: |
          CURRENT_VERSION=$(sed -n '2p' control | sed 's/.*://' | xargs) # get current version from control file
          NEXTVERSION=$(echo ${CURRENT_VERSION} | awk -F. -v OFS=. '{$NF += 1 ; print}') # bump version
          sed -i "2s/.*/Version: ${NEXTVERSION}/" control # update version in control file

      - name: Creating debian package
        run: bash pack-deb.sh

      - name: Updating files in main repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          commit_message: Update files in main repo
          # Only include needed files
          file_pattern: 'control last_commit_sha.txt'

      - name: Deploying repo
        uses: smeinecke/apt-repo-action@v2.1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo_supported_arch: amd64
          repo_supported_version: |
            kinetic
            jammy
            stable
          file: eupnea-utils*.deb
          file_target_version: kinetic
          public_key: ${{ secrets.PUBLIC }}
          private_key: ${{ secrets.PRIVATE }}
          key_passphrase: ""
          repo_folder: "debian_ubuntu"
