name: Deploying apt repo
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "10 0 * * *" # run at the start of every day after postinstall scripts repo update
  workflow_dispatch:

jobs:
  check-sha:
    runs-on: ubuntu-22.04
    steps:
      - name: Checking out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      - name: Run postinstall scripts update check
        id: update-check
        # This oneliner compares the locally stored commit has agains the latest one at the postinstall repo and returns either true or false
        run: |
          echo "remote_sha=$(curl -s https://api.github.com/repos/eupnea-linux/postinstall-scripts/commits/main | jq -r '.sha')" >> $GITHUB_OUTPUT
          echo "results_of_check=$([[ '$(cat latest_commit_sha.txt)' == '${{ env.remote_sha }}' ]] && echo 'true' || echo 'false')"
        
      - name: Check results of update check
        if: steps.git-check.outputs.results == 'true'
        run: exit 0 # exit sucessfully
      
  deploy-repo:
    runs-on: ubuntu-22.04
    needs: check-sha # only run if check-sha was successfull
    steps:
      
      - name: Update local commit sha
        run: echo "${{ env.remote_sha }}" > ./last_commit_sha.txt
      
      - name: Bump version in control file
        run: |
          CURRENT_VERSION=$(sed -n '2p' control | sed 's/.*://' | xargs) # get current version from control file
          NEXTVERSION=$(echo ${CURRENT_VERSION} | awk -F. -v OFS=. '{$NF += 1 ; print}') # bump version
          sed -i "2s/.*/Version: ${NEXTVERSION}/" control # update version in control file

      - name: Creating debian package
        run: bash pack-deb.sh

      - name: Updating files in main repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          commit_message: Update files in main repo
          # Only include needed files
          file_pattern: 'control last_commit_sha.txt'

      - name: Deploying repo
        uses: smeinecke/apt-repo-action@v2.1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo_supported_arch: amd64
          repo_supported_version: |
            kinetic
            jammy
            stable
          file: eupnea-utils*.deb
          file_target_version: kinetic
          public_key: ${{ secrets.PUBLIC }}
          private_key: ${{ secrets.PRIVATE }}
          key_passphrase: ""
          repo_folder: "debian_ubuntu"
