name: Updating system package
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * *" # run at the start of every day
  workflow_dispatch:

jobs:
  check-sha:
    runs-on: ubuntu-22.04
    outputs:
      match_results: ${{ steps.check-shas.outputs.match_results }}
      remote_sha: ${{ steps.check-shas.outputs.remote_sha }}
    steps:
      - name: Checking out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Download remote commit shas
        id: check-shas
        run: |
          # Download remote sha
          latest_sha=$(curl -s https://api.github.com/repos/eupnea-linux/system-update/commits/main | jq -r '.sha')
          
          # Check remote sha against cached one
          match_results=$([[ "$(cat system_sha-cache.txt)" == "$latest_sha" ]] && echo "true" || echo "false")
          echo "match_results=$match_results" >> $GITHUB_OUTPUT
          
          # Add sha to output
          echo "remote_sha=$latest_sha" >> $GITHUB_OUTPUT

  deploy-repo:
    runs-on: ubuntu-22.04
    needs: check-sha # needs for the vars from the previous job
    # Only run script when remote sha has changed, aka the results DON'T match
    if: needs.check-sha.outputs.match_results == 'false'
    steps:
      - name: Checking out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Update local commits sha file
        run: |
          echo "${{ needs.check-sha.outputs.remote_sha }}" > system_sha-cache.txt

      - name: Bump version in system control file
        run: |
          CURRENT_VERSION=$(sed -n '2p' system-control | sed 's/.*://' | xargs) # get current version from control file
          NEXTVERSION=$(echo ${CURRENT_VERSION} | awk -F. -v OFS=. '{$NF += 1 ; print}') # bump version
          sed -i "2s/.*/Version: ${NEXTVERSION}/" system-control # update version in control file

      - name: Creating system deb package
        run: bash pack-system.sh

      - name: Updating files in main branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          commit_message: Update files in main branch
          # Only include needed files
          file_pattern: 'system-control system_sha-cache.txt'

      - name: Adding system packages
        uses: smeinecke/apt-repo-action@v2.1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo_supported_arch: amd64
          repo_supported_version: |
            kinetic
            jammy
            stable
          file: eupnea-system*.deb
          file_target_version: |
            kinetic
            jammy
            stable
          public_key: ${{ secrets.PUBLIC }}
          private_key: ${{ secrets.PRIVATE }}
          key_passphrase: ""
          repo_folder: "debian_ubuntu"
